# Generated by Django 6.1.1 on 2026-09-26 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('INR', 'INR (₹)'), ('USD', 'USD ($)'), ('GBP', 'GBP (£)'), ('EUR', 'EUR (€)'), ('JPY', 'JPY (¥)'), ('CNY', 'CNY (¥)'), ('CAD', 'CAD ($)'), ('AUD', 'AUD ($)'), ('CHF', 'CHF'), ('SGD', 'SGD (S$)'), ('AED', 'AED (د.إ)'), ('SAR', 'SAR (ر.س)'), ('KRW', 'KRW (₩)'), ('NZD', 'NZD (NZ$)'), ('ZAR', 'ZAR (R)'), ('BRL', 'BRL (R$)'), ('MXN', 'MXN ($)'), ('THB', 'THB (฿)'), ('MYR', 'MYR (RM)'), ('IDR', 'IDR (Rp)')], default='INR', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
